### ISSUE TITLE
[Epic] Sign Deliveries of CA version 12.3

### ISSUE THREAD

**Issue by InbalZilberman** [Conjurinc-workato-dev/appliance#74]
### Feature Overview & Customer Need
The deliverables we place in the CA safe should be signed.
I have contacted Gil Goldberger to learn that tars are not signed today if this is the case the dockerless tar should be changed to zip.
Please make sure **any other delivery provided** excluding docs in this Safe should be signed also.

In Summary,  sign our delivery.
### Sharing is Caring
Share the knowledge in conf and demo with the whole Conjur group (US also) and present them the process.
### Release
Place the signed zip in the safe of CA

**Comment by maxAtSW** [comment]
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6741
